import "./globals.css";
import { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/app/libs";

import { AppProvider } from "./providers";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Cloud Firestore chat app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
